# Generated by Django 2.2.2 on 2020-08-29 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_auto_20200829_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='mobile',
            field=models.CharField(default=1234567890, max_length=12, unique=True),
            preserve_default=False,
        ),
    ]
